#!/usr/bin/env bash
# Vector stores and similarity retrieval. Qdrant is a specialized local
# vector database. This demo creates a collection, inserts tiny hand-written
# embeddings, runs nearest-neighbor retrieval, then adds a metadata filter.
set -euo pipefail
source "$(dirname "$0")/../../scripts/lib.sh"
set -euo pipefail

QDRANT="http://localhost:${QDRANT_HTTP_PORT:-6333}"
COLLECTION="docs"

api() {
  curl -fsS "$@"
}

pretty() {
  python3 -m json.tool 2>/dev/null || cat
}

show_results() {
  python3 -c 'import json, sys
body = json.load(sys.stdin)
for item in body.get("result", []):
    payload = item.get("payload", {})
    print("id={} score={:.4f} title={} category={}".format(item.get("id"), item.get("score"), payload.get("title"), payload.get("category")))'
}

echo "${BOLD}Vector stores and similarity retrieval${RESET}"
note "Assumes 'make vector-store' is running (base + Qdrant)."

step "Wait for Qdrant" "the vector database must answer before we create a collection"
qdrant_ready=0
for _ in $(seq 1 60); do
  if curl -fsS "$QDRANT/readyz" >/dev/null 2>&1; then
    qdrant_ready=1
    break
  fi
  sleep 1
done
if [ "$qdrant_ready" != "1" ]; then
  echo "Qdrant did not answer at $QDRANT. Run 'make vector-store' and check 'docker compose ps qdrant'." >&2
  exit 1
fi
run "curl -fsS $QDRANT/readyz"
pause

step "Create a vector collection" "all vectors have the same dimension and distance metric"
run "api -X DELETE '$QDRANT/collections/$COLLECTION' >/dev/null 2>&1 || true"
run "api -X PUT '$QDRANT/collections/$COLLECTION' -H 'Content-Type: application/json' -d '{\"vectors\":{\"size\":4,\"distance\":\"Cosine\"}}' | pretty"
pause

step "Insert example embeddings" "vectors plus payload metadata"
api -X PUT "$QDRANT/collections/$COLLECTION/points?wait=true" \
  -H 'Content-Type: application/json' \
  -d '{
    "points": [
      {"id": 1, "vector": [0.10, 0.90, 0.10, 0.00], "payload": {"title": "cache aside", "category": "systems"}},
      {"id": 2, "vector": [0.15, 0.85, 0.15, 0.05], "payload": {"title": "job queue", "category": "systems"}},
      {"id": 3, "vector": [0.90, 0.10, 0.00, 0.10], "payload": {"title": "banana smoothie", "category": "food"}},
      {"id": 4, "vector": [0.88, 0.12, 0.05, 0.09], "payload": {"title": "apple pie", "category": "food"}}
    ]
  }' | pretty
pause

step "Query by vector similarity" "a systems-like query should retrieve systems examples first"
api -X POST "$QDRANT/collections/$COLLECTION/points/search" \
  -H 'Content-Type: application/json' \
  -d '{"vector": [0.12, 0.88, 0.10, 0.02], "limit": 4, "with_payload": true}' \
  | show_results
pause

step "Add a metadata filter" "structured filters constrain which vectors are eligible"
note "The query vector is still systems-like, but the filter only allows category=food."
api -X POST "$QDRANT/collections/$COLLECTION/points/search" \
  -H 'Content-Type: application/json' \
  -d '{
    "vector": [0.12, 0.88, 0.10, 0.02],
    "limit": 4,
    "with_payload": true,
    "filter": {"must": [{"key": "category", "match": {"value": "food"}}]}
  }' \
  | show_results
pause

step "What this proves" "vector similarity and metadata filtering solve different parts"
note "The first query ranks nearby vectors by similarity."
note "The filtered query restricts the candidate set before returning nearest eligible points."
note "In production, vectors are generated by embedding models and payload filters enforce tenant, permission, and category boundaries."

echo
echo "${BOLD}Done.${RESET} Cleanup: ${GREEN}make reset${RESET}"
